/*
 * Staging tables - file 1 of 3
 * Generated by Dataverse Migration Scaffolder (test fixture)
 */

DROP TABLE IF EXISTS [dbo].[stage_contoso_Category];
CREATE TABLE [dbo].[stage_contoso_Category](
    [contoso_activedate] DATETIME2(7),
    [contoso_category] NVARCHAR(100),
    [contoso_categorycode] NVARCHAR(100),
    [contoso_categoryid] NVARCHAR(100),
    [contoso_expirationdate] DATETIME2(7),
    [contoso_formid] NVARCHAR(100),
    [contoso_legacyid] NVARCHAR(100),
    [overriddencreatedon] DATETIME2(7),
    [ownerid] NVARCHAR(100),
    [owneridtype] NVARCHAR(100),
    [statecode] INT,
    [tablename] NVARCHAR(100) DEFAULT 'stage_contoso_Category'
);

DROP TABLE IF EXISTS [dbo].[stage_contoso_Court];
CREATE TABLE [dbo].[stage_contoso_Court](
    [contoso_courtid] NVARCHAR(100),
    [contoso_name] NVARCHAR(100),
    [overriddencreatedon] DATETIME2(7),
    [ownerid] NVARCHAR(100),
    [owneridtype] NVARCHAR(100),
    [statecode] INT,
    [tablename] NVARCHAR(100) DEFAULT 'stage_contoso_Court'
);
