/*
 * Staging tables - file 3 of 3
 * Generated by Dataverse Migration Scaffolder (test fixture)
 */

DROP TABLE IF EXISTS [dbo].[stage_contoso_Incident];
CREATE TABLE [dbo].[stage_contoso_Incident](
    [contoso_caseid] NVARCHAR(100),    -- lookup: contoso_case
    [contoso_incidentid] NVARCHAR(100),
    [contoso_legacyid] NVARCHAR(100),
    [contoso_name] NVARCHAR(100),
    [contoso_narrative] NVARCHAR(MAX),
    [overriddencreatedon] DATETIME2(7),
    [ownerid] NVARCHAR(100),
    [owneridtype] NVARCHAR(100),
    [statecode] INT,
    [tablename] NVARCHAR(100) DEFAULT 'stage_contoso_Incident'
);
