/*
 * Staging tables - file 2 of 3
 * Generated by Dataverse Migration Scaffolder (test fixture)
 */

DROP TABLE IF EXISTS [dbo].[stage_contoso_Case];
CREATE TABLE [dbo].[stage_contoso_Case](
    [contoso_bailamount] NVARCHAR(100),
    [contoso_bailamount_base] NVARCHAR(100),
    [contoso_caseid] NVARCHAR(100),
    [contoso_categoryid] NVARCHAR(100),    -- lookup: contoso_category
    [contoso_courtid] NVARCHAR(100),    -- lookup: contoso_court
    [contoso_filedon] DATE,
    [contoso_incidentid] NVARCHAR(100),
    [contoso_incidentidtype] NVARCHAR(100),
    [contoso_legacyid] NVARCHAR(100),
    [contoso_name] NVARCHAR(200),
    [contoso_priority] NVARCHAR(100),
    [contoso_sealed] BIT,
    [overriddencreatedon] DATETIME2(7),
    [ownerid] NVARCHAR(100),
    [owneridtype] NVARCHAR(100),
    [statecode] INT
);
