/*
 * GUID mapping tables - file 1 of 3
 * Generated by Dataverse Migration Scaffolder (test fixture)
 */

IF OBJECT_ID(N'[dbo].[guid_contoso_Category]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[guid_contoso_Category](
        [contoso_categoryid] VARCHAR(100) NULL,
        [contoso_category] NVARCHAR(100) NULL,
        [contoso_legacyid] NVARCHAR(100) NULL,
        [statecode] INT NULL
    );
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_guid_contoso_Category_contoso_legacyid' AND [object_id] = OBJECT_ID(N'[dbo].[guid_contoso_Category]'))
    CREATE NONCLUSTERED INDEX [IX_guid_contoso_Category_contoso_legacyid] ON [dbo].[guid_contoso_Category]([contoso_legacyid]);

IF OBJECT_ID(N'[dbo].[guid_contoso_Court]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[guid_contoso_Court](
        [contoso_courtid] VARCHAR(100) NULL,
        [contoso_name] NVARCHAR(100) NULL,
        [statecode] INT NULL
    );
END
