/*
 * GUID mapping tables - file 3 of 3
 * Generated by Dataverse Migration Scaffolder (test fixture)
 */

IF OBJECT_ID(N'[dbo].[guid_contoso_Incident]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[guid_contoso_Incident](
        [contoso_incidentid] VARCHAR(100) NULL,
        [contoso_caseid] NVARCHAR(100) NULL,
        [contoso_legacyid] NVARCHAR(100) NULL,
        [contoso_name] NVARCHAR(100) NULL,
        [statecode] INT NULL
    );
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_guid_contoso_Incident_contoso_legacyid' AND [object_id] = OBJECT_ID(N'[dbo].[guid_contoso_Incident]'))
    CREATE NONCLUSTERED INDEX [IX_guid_contoso_Incident_contoso_legacyid] ON [dbo].[guid_contoso_Incident]([contoso_legacyid]);
