/*
 * GUID mapping tables - file 2 of 3
 * Generated by Dataverse Migration Scaffolder (test fixture)
 */

IF OBJECT_ID(N'[dbo].[guid_contoso_Case]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[guid_contoso_Case](
        [contoso_caseid] VARCHAR(100) NULL,
        [contoso_categoryid] NVARCHAR(100) NULL,
        [contoso_courtid] NVARCHAR(100) NULL,
        [contoso_incidentid] NVARCHAR(100) NULL,
        [contoso_legacyid] NVARCHAR(100) NULL,
        [contoso_name] NVARCHAR(200) NULL,
        CONSTRAINT [UQ_guid_contoso_Case_contoso_legacyid] UNIQUE ([contoso_legacyid])
    );
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE [name] = N'IX_guid_contoso_Case_contoso_legacyid' AND [object_id] = OBJECT_ID(N'[dbo].[guid_contoso_Case]'))
    CREATE NONCLUSTERED INDEX [IX_guid_contoso_Case_contoso_legacyid] ON [dbo].[guid_contoso_Case]([contoso_legacyid]);
